//------------------------------------------------------------------------------
// <auto-generated>
//    이 코드는 템플릿에서 생성되었습니다.
//
//    이 파일을 수동으로 변경하면 응용 프로그램에 예기치 않은 동작이 발생할 수 있습니다.
//    코드가 다시 생성되면 이 파일에 대한 수동 변경 사항을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyReportOracleDB.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DR_BULKBM> DR_BULKBM { get; set; }
        public DbSet<DR_CONSISTENCY> DR_CONSISTENCY { get; set; }
        public DbSet<DR_CONSISTENCY_INSTRUMENT> DR_CONSISTENCY_INSTRUMENT { get; set; }
        public DbSet<DR_CONSISTENCY_SPECIALTY> DR_CONSISTENCY_SPECIALTY { get; set; }
        public DbSet<DR_CONSISTENCY_VALVE> DR_CONSISTENCY_VALVE { get; set; }
        public DbSet<DR_INSTRUMENTBM> DR_INSTRUMENTBM { get; set; }
        public DbSet<DR_ISODESCRIPTION> DR_ISODESCRIPTION { get; set; }
        public DbSet<DR_ISOREV> DR_ISOREV { get; set; }
        public DbSet<DR_LINELIST> DR_LINELIST { get; set; }
        public DbSet<DR_LINENOISO> DR_LINENOISO { get; set; }
        public DbSet<DR_MODELPROGRESS_INSTRUMENT> DR_MODELPROGRESS_INSTRUMENT { get; set; }
        public DbSet<DR_MODELPROGRESS_LINE> DR_MODELPROGRESS_LINE { get; set; }
        public DbSet<DR_MODELPROGRESS_PART> DR_MODELPROGRESS_PART { get; set; }
        public DbSet<DR_MODELPROGRESS_RUN> DR_MODELPROGRESS_RUN { get; set; }
        public DbSet<DR_PROGRESS_CPIPINGLINELIST> DR_PROGRESS_CPIPINGLINELIST { get; set; }
        public DbSet<DR_PROGRESS_PIPINGLINELIST> DR_PROGRESS_PIPINGLINELIST { get; set; }
        public DbSet<DR_SPECIALTYBM> DR_SPECIALTYBM { get; set; }
        public DbSet<DR_SUPPORTBM> DR_SUPPORTBM { get; set; }
    }
}
