//------------------------------------------------------------------------------
// <auto-generated>
//    이 코드는 템플릿에서 생성되었습니다.
//
//    이 파일을 수동으로 변경하면 응용 프로그램에 예기치 않은 동작이 발생할 수 있습니다.
//    코드가 다시 생성되면 이 파일에 대한 수동 변경 사항을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyReportOracleDB.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DR_BULKBM
    {
        public decimal NUM { get; set; }
        public string OID { get; set; }
        public string DWGNO { get; set; }
        public string SPECNAME { get; set; }
        public string INDUSTRYCOMMODITYCODE { get; set; }
        public string PART { get; set; }
        public string LONGMATERIALDESCRIPTION { get; set; }
        public string COMMENTS { get; set; }
        public string PARTNUMBER { get; set; }
        public string FABRICATIONTYPE { get; set; }
    }
}
