//------------------------------------------------------------------------------
// <auto-generated>
//    이 코드는 템플릿에서 생성되었습니다.
//
//    이 파일을 수동으로 변경하면 응용 프로그램에 예기치 않은 동작이 발생할 수 있습니다.
//    코드가 다시 생성되면 이 파일에 대한 수동 변경 사항을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyReportOracleDB.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DR_CONSISTENCY
    {
        public DR_CONSISTENCY()
        {
            this.DR_CONSISTENCY_INSTRUMENT = new HashSet<DR_CONSISTENCY_INSTRUMENT>();
            this.DR_CONSISTENCY_SPECIALTY = new HashSet<DR_CONSISTENCY_SPECIALTY>();
            this.DR_CONSISTENCY_VALVE = new HashSet<DR_CONSISTENCY_VALVE>();
        }
    
        public string LINENO { get; set; }
    
        public virtual ICollection<DR_CONSISTENCY_INSTRUMENT> DR_CONSISTENCY_INSTRUMENT { get; set; }
        public virtual ICollection<DR_CONSISTENCY_SPECIALTY> DR_CONSISTENCY_SPECIALTY { get; set; }
        public virtual ICollection<DR_CONSISTENCY_VALVE> DR_CONSISTENCY_VALVE { get; set; }
    }
}
