//------------------------------------------------------------------------------
// <auto-generated>
//    이 코드는 템플릿에서 생성되었습니다.
//
//    이 파일을 수동으로 변경하면 응용 프로그램에 예기치 않은 동작이 발생할 수 있습니다.
//    코드가 다시 생성되면 이 파일에 대한 수동 변경 사항을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyReportOracleDB.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DR_ISOREV
    {
        public string DWGNO { get; set; }
        public string REV_NO { get; set; }
        public string REV_DATE { get; set; }
        public string DWN { get; set; }
        public string CHKD { get; set; }
        public string AAPD { get; set; }
        public string PLANT { get; set; }
        public string AREA { get; set; }
        public string UNIT { get; set; }
        public decimal NUM { get; set; }
    }
}
