//------------------------------------------------------------------------------
// <auto-generated>
//    이 코드는 템플릿에서 생성되었습니다.
//
//    이 파일을 수동으로 변경하면 응용 프로그램에 예기치 않은 동작이 발생할 수 있습니다.
//    코드가 다시 생성되면 이 파일에 대한 수동 변경 사항을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyReportOracleDB.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DR_LINELIST
    {
        public string OID { get; set; }
        public string PIPELINE { get; set; }
        public string DWGNO { get; set; }
        public string DESIGN_PRESS { get; set; }
        public string OPER_PRESS { get; set; }
        public string TEST_PRESS { get; set; }
        public string DESIGN_TEMP { get; set; }
        public string OPER_TEMP { get; set; }
        public string INSUL_CODE { get; set; }
        public string INSUL_THK { get; set; }
        public string PAINT_CODE { get; set; }
        public string RTPT { get; set; }
        public string PWHT { get; set; }
        public string TEST_MEDIUM { get; set; }
        public string STEAM_TRACE { get; set; }
        public string STEAM_JACKETING { get; set; }
        public string ELECTRIC_TRACE { get; set; }
        public string STRESS_ANALYSIS { get; set; }
        public string CLEANING { get; set; }
        public string PIPING_PID { get; set; }
        public string PIPING_PLAN { get; set; }
        public string PIPING_STRESS { get; set; }
        public decimal NUM { get; set; }
    }
}
